cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

env: DISPLAY=:99.0

services:
  - xvfb
  - docker

addons:
  sonarcloud:
    organization: "fede-vaccaro"
token:
  secure: $SONAR_TOKEN
  language: java

jdk: openjdk8

matrix:
  include:
    - if: type = cron
      env: PIT_MAVEN_ARGS="org.pitest:pitest-maven:mutationCoverage"
    - if: type = push
      env: PIT_MAVEN_ARGS=""
    

install: true

before_script:
   - sh -e /etc/init.d/xvfb start

script:
  -  travis_wait 360 mvn -f com.unifiprojects.app.appichetto/pom.xml clean test verify coveralls:report sonar:sonar $PIT_MAVEN_ARGS
