cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

env: DISPLAY=:99.0

services:
  - xvfb
  - docker

addons:
  sonarcloud:
    organization: "fede-vaccaro"
token:
  secure: $SONAR_TOKEN
  language: java

jdk: openjdk8

matrix:
  include:
    - if: type = cron
      env: PIT_MAVEN_ARGS="-P run-PIT"
    - if: type = push
      env: PIT_MAVEN_ARGS=""
    

install: true

script:
  -  mvn -f aggregator-module/pom.xml clean test verify coveralls:report sonar:sonar -Dsonar.projectKey=fede-vaccaro_APT-project $PIT_MAVEN_ARGS

