cache:
 directories:
  - $HOME/.m2
  - $HOME/.sonar/cache

env: DISPLAY=:99.0

addons:
 sonarcloud:  
  organization: "fede-vaccaro"
token:
  secure: $SONAR_TOKEN
  language: java

jdk: openjdk8

install: true

before_script:
- sh -e /etc/init.d/xvfb start

script:
 - mvn -f com.unifiprojects.app.appichetto/pom.xml clean verify coveralls:report sonar:sonar
