cache:
 directories:
  - $HOME/.m2
  - $HOME/.sonar/cache

addons:
 sonarcloud:  
  organization: "fede-vaccaro"
token:
  secure: $SONAR_TOKEN
  language: java

jdk: openjdk8

install: true

script:
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=fede-vaccaro_APT-project
