version: "2"
services:

  db:
   image: postgres:10
   restart: always
   ports:
    - 5432:5432
   environment:
    POSTGRES_USER: docker
    POSTGRES_PASSWORD: docker
    POSTGRES_DB: docker
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080